# Generated by Django 4.2.3 on 2024-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('1000-2000', '1000-2000'), ('2000-3000', '2000-3000'), ('3000-4000', '3000-4000'), ('4000-5000', '4000-5000'), ('5000-6000', '5000-6000'), ('6000-7000', '6000-7000'), ('7000-8000', '7000-8000'), ('8000-9000', '8000-9000'), ('9000-10000', '9000-10000'), ('10000-11000', '10000-11000'), ('11000-12000', '11000-12000'), ('12000-13000', '12000-13000'), ('13000-14000', '13000-14000'), ('14000-15000', '14000-15000'), ('15000-16000', '15000-16000'), ('16000-17000', '16000-17000'), ('17000-18000', '17000-18000'), ('18000-19000', '18000-19000'), ('19000-20000', '19000-20000')], max_length=60)),
            ],
        ),
    ]
